version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT=klizmanzapata
    #   - MONGO_INITDB_ROOT_PASSWORD=klizman1999
    volumes:
      - ./mongo_data:/data/db
